name: Deploy to Amazon S3

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches: [$default-branch]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up mise
        uses: jdx/mise-action@v2

      - name: Install Deps & Build
        env:
          VITE_RELEASE_VERSION: ${{ github.sha }}
        run: |
          yarn
          yarn build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_BUCKET_NAME }} --delete --exclude "*.map" --exclude "*.gz" --exclude "*.br"
          aws s3 cp ./dist/index.html s3://${{ secrets.AWS_BUCKET_NAME }}/index.html --metadata-directive REPLACE --cache-control max-age=0
          aws s3 cp ./dist/index.html s3://${{ secrets.AWS_BUCKET_NAME }}/index.html.gz --content-encoding gzip --content-type text/html --metadata-directive REPLACE --cache-control max-age=0
          aws s3 cp ./dist/index.html s3://${{ secrets.AWS_BUCKET_NAME }}/index.html.br --content-encoding br --content-type text/html --metadata-directive REPLACE --cache-control max-age=0
